[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Adds SCP 3199, the Humans, Refuted to Lethal Company as a new enemy [V56 Compatible]"
websiteUrl = "https://github.com/FelixAllard/SCP3199LC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
TheWeavers-LethalBestiary = "1.2.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/ProjectSCP.SCP3199.dll"
target = "plugins/SCP3199/"

[[build.copy]]
source = "../../SCP3199/AssetBundles/StandaloneWindows/scp3199modassets"
target = "plugins/SCP3199/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]